
# Screen
WIDTH, HEIGHT = 1280, 720
TITLE = 'The Lost Penguin'

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
HITBOX_COLOR = (255, 0, 0)

# Map
TILESIZE = 64
MAIN_WORLD_BACKGROUND = 'main_world'
TEST = 'test'

# Buttons
BACK_OFFSET = (0, 30)
# Player
START_X = 17
START_Y = 11
SCALE = 64
WALK_COUNT_MAX = 30
WALK_SPEED = WALK_COUNT_MAX//5
TIME_ATTACKING = 30

# Text
TEXT_FONT = 'Berlin Sans FB'
OPTION_FONT_SIZE = 60

# Score
SCORE_FONT_SIZE = 70
SCORE_OFFSET = 10
SCORE_POSITION = (WIDTH - SCORE_FONT_SIZE, 0)

# Life
LIFE_SCALE = 64
LIFE_OFFSET = 10
LIFE_POSITION = [LIFE_OFFSET, LIFE_OFFSET]

# Enemy

ENEMY_WALK_COUNT_MAX = 30
ENEMY_WALK_SPEED = ENEMY_WALK_COUNT_MAX//5
TIME_TILL_DAMAGE = 200                              # 100 ~ 1 secunda

BAT_SCALE = 60
BAT_VELOCITY = 2
RADIUS = 200
BAT_RADIUS = 150
BAT_DAMAGE = 1
BAT_SCORE = 10

# Penguin
PENGUIN_VELOCITY = 3
PENGUIN_MAX_LIFE = 6

# Hitboxes
PENGUIN_HITBOX_OFFSET = (15, 10)
PENGUIN_HITBOX = (35, 50)

BAT_HITBOX_OFFSET = (10, 10)
BAT_HITBOX = (40, 30)

# Camera
CAMERA_SMOOTH = 20
REDUCE = 5
CAMERA_BOUNDARIES_SMOOTH = 1.07
EPSILON = 1e-10

# Weapons
WEAPON_SCALE = (11, 43)
WEAPON_OFFSET_RIGHT = (40, 0)
WEAPON_OFFSET_LEFT = (13, 0)
WEAPON_OFFSET_UP = (30, -10)
WEAPON_OFFSET_DOWN = (40, 0)
MAX_SWING = 180
SPEED_ATTACK = 5
START_ANGLE_LEFT = 0
START_ANGLE_RIGHT = 0
START_ANGLE_UP = 90
START_ANGLE_DOWN = 90
